/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ga_graphics_NativeShaderFactory */

#ifndef _Included_ga_graphics_NativeShaderFactory
#define _Included_ga_graphics_NativeShaderFactory
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    check_support
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ga_graphics_NativeShaderFactory_check_1support
  (JNIEnv *, jclass);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    get_max_texture_units
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ga_graphics_NativeShaderFactory_get_1max_1texture_1units
  (JNIEnv *, jclass);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    compile_shader
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ga_graphics_NativeShaderFactory_compile_1shader
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    delete_shader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_delete_1shader
  (JNIEnv *, jclass, jint);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    bind_shader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_bind_1shader
  (JNIEnv *, jclass, jint);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    nglUseProgramObjectARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_nglUseProgramObjectARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    nglUniform1iARB
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_nglUniform1iARB
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    nglActiveTextureARB
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_nglActiveTextureARB
  (JNIEnv *, jclass, jint);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    get_parameter
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ga_graphics_NativeShaderFactory_get_1parameter
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    set_parameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_set_1parameterf
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    set_parameter2f
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_set_1parameter2f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    set_parameter3f
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_set_1parameter3f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    set_parameter4f
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_set_1parameter4f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     ga_graphics_NativeShaderFactory
 * Method:    set_parameterMatrix4f
 * Signature: (IIFFFFFFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_ga_graphics_NativeShaderFactory_set_1parameterMatrix4f
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
