/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ga_graphics_NativeShaderFactory_NativeShaderImpl */

#ifndef _Included_ga_graphics_NativeShaderFactory_NativeShaderImpl
#define _Included_ga_graphics_NativeShaderFactory_NativeShaderImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef ga_graphics_NativeShaderFactory_NativeShaderImpl_GL_TEXTURE0_ARB
#define ga_graphics_NativeShaderFactory_NativeShaderImpl_GL_TEXTURE0_ARB 33984L
#ifdef __cplusplus
}
#endif
#endif
